version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    links:
      - persistence
    depends_on:
      - persistence
  persistence:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
